apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    internal-service-port27017: ClusterIP
    external-service-port27017: NodePort
spec:
  containers:
    - name: mongo
      image: mongo
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: root
      ports:
        - containerPort: 27017
